adminapp/urls.py
import adminapp.views as admin_views
from django.urls import path


app_name = 'adminapp'

urlpatterns = [
    # user
    path('users/create/', admin_views.user_create, name='user_create'),
    path('users/', admin_views.UsersListView.as_view(), name='user_list'),
    path('users/update/<int:pk>/', admin_views.user_update, name='user_update'),
    path('users/delete/<int:pk>/', admin_views.user_delete, name='user_delete'),

    # categories_product
    path('categories/create/', admin_views.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/', admin_views.categories, name='category_list'),
    path('categories/update/<int:pk>/', admin_views.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', admin_views.category_delete, name='category_delete'),
    # product
    path('products/create/<int:pk>/', admin_views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/', admin_views.ProductsListView.as_view(), name='product_list'),
    path('products/detail/<int:pk>/', admin_views.product_detail, name='product_detail'),
    path('products/update/<int:pk>/', admin_views.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', admin_views.ProductDeleteView.as_view(), name='product_delete'),

]

authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

cathouseshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainapp import views as mainapp


urlpatterns = [
    path('control/', admin.site.urls),
    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', include('adminapp.urls', namespace='adminapp'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):  # форма для работы с пользователем
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from authapp.forms import ShopUserRegisterForm
from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm
from authapp.models import ShopUser
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from mainapp.models import Product, ProductCategory
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView


class AccessMixin:  # проверка на  is_superuser

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

# user


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):

    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)

        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_list'))
    else:
        user_form = ShopUserRegisterForm()

    context = {
        'title': title,
        'form': user_form
    }
    return render(request, 'adminapp/user_form.html', context=context)


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     context = {
#         'title': 'админка/пользователи',
#         'object_list': ShopUser.objects.all().order_by('-is_active')
#     }
#     return render(request, 'adminapp/users.html', context=context)

class UsersListView(ListView, AccessMixin):
    model = ShopUser  # название класса модели
    template_name = 'adminapp/users.html'  # путь к шаблону


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        user_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)

        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_list'))
    else:
        user_form = ShopUserAdminEditForm(instance=edit_user)

    context = {
        'title': title,
        'form': user_form
    }
    return render(request, 'adminapp/user_form.html', context=context)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'

    edit_user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        if edit_user.is_active:
            edit_user.is_active = False  # деактивируем пользователя
        else:
            edit_user.is_active = True
        edit_user.save()
        return HttpResponseRedirect(reverse('adminapp:user_list'))
    context = {
        'title': title,
        'object': edit_user
    }
    return render(request, 'user_delete.html', context=context)

# category


# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     title = 'категории/создание'
#
#     if request.method == 'POST':
#         category_form = ProductCategoryEditForm(request.POST, request.FILES)
#
#         if category_form.is_valid():
#             category_form.save()
#             return HttpResponseRedirect(reverse('adminapp:categories'))
#     else:
#         category_form = ProductCategoryEditForm()
#
#     context = {
#         'title': title,
#         'form': category_form
#     }
#     return render(request, 'adminapp/category_create.html', context=context)

class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_create.html'
    success_url = reverse_lazy('adminapp:categories')
    fields = '__all__'


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    context = {
        'title': 'админка/категории',
        'object_list': ProductCategory.objects.all().order_by('-is_active')
    }
    return render(request, 'adminapp/categories.html', context=context)


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     title = 'категории/редактирование'
#
#     edit_category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         edit_form = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('adminapp:category_list'))
#     else:
#         edit_form = ProductEditForm(instance=edit_category)
#     context = {
#         'title': title,
#         'form': edit_form,
#     }
#     return render(request, 'adminapp/category_update.html', context)

class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('adminapp:category_list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'

        return context


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request, pk):
    title = 'категории/удаление'

    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        category.is_active = False
        category.save()
        return HttpResponseRedirect(reverse("adminapp:category_list"))

    content = {
        'title': title,
        'object': category
    }

    return render(request, "adminapp/category_delete.html", content)

# product


# @user_passes_test(lambda u: u.is_superuser)
# def product_create(request, pk):
#     title = 'продукты/создание'
#     category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         product_form = ProductEditForm(request.POST, request.files)
#         if product_form.is_valid():
#             product_form.save()
#             return HttpResponseRedirect(reverse('adminapp:product_list', args=[pk]))
#     else:
#         product_form = ProductEditForm(initial={'category': category})
#     context = {
#         'title': title,
#         'update_form': product_form,
#         'category': category
#     }
#     return render(request, 'adminapp/product_update.html', context=context)


class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductEditForm
    # success_url = reverse_lazy('adminapp:product_list')

    def get_success_url(self):
        return reverse('adminapp:product_list', args=[self.kwargs['pk']])


# @user_passes_test(lambda u: u.is_superuser)
# def products(request, pk):
#     title = 'продукты/подробнее'
#     context = {
#         'title': title,
#         'category': get_object_or_404(ProductCategory, pk=pk),
#         'object_list': Product.objects.filter(category__pk=pk).order_by('-is_active')
#     }
#     return render(request, 'adminapp/products.html', context=context)

class ProductsListView(ListView, AccessMixin):
    model = Product
    template_name = 'adminapp/products.html'

    def get_context_data(self, *args, **kwargs):  # выбор нужной категории
        context_data = super().get_context_data(*args, **kwargs)
        context_data['category'] = get_object_or_404(ProductCategory, pk=self.kwargs.get('pk'))
        return context_data

    def get_queryset(self):  # выбор товаров нужной категории
        return Product.objects.filter(category__pk=self.kwargs.get('pk'))


# @user_passes_test(lambda u: u.is_superuser)
# def product_update(request, pk):
#     title = 'продукт/редактирование'
#     edit_product = get_object_or_404(Product, pk=pk)
#     if request.method == 'POST':
#         edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
#         if edit_form.is_valid():
#             edit_form.save()
#             return HttpResponseRedirect(reverse('adminapp:product_list', args=[edit_product.pk]))
#     else:
#         edit_form = ProductEditForm(instance=edit_product)
#     context = {
#         'title': title,
#         'update_form': edit_form,
#         'category': edit_product.category
#     }
#     return render(request, 'adminapp/product_update.html', context)

class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product_form.html'
    form_class = ProductEditForm
    # success_url = reverse_lazy('adminapp:product_list')

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])


# @user_passes_test(lambda u: u.is_superuser)
# def product_delete(request, pk):
#     title = 'продукт/удаление'
#     product = get_object_or_404(Product, pk=pk)
#     if request.method == 'POST':
#         product.is_active = False
#         product.save()
#         return HttpResponseRedirect(reverse('adminapp:product_list', args=[product.category.pk]))
#     context = {
#         'title': title,
#         'product_to_delete': product
#     }
#     return render(request, 'adminapp/product_delete.html', context)

class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'

    def get_success_url(self):
        product_item = Product.objects.get(pk=self.kwargs['pk'])
        return reverse('adminapp:product_list', args=[product_item.category_id])




@user_passes_test(lambda u: u.is_superuser)
def product_detail(request, pk):
    title = 'продукт/подробнее'
    product = get_object_or_404(Product, pk=pk)
    context = {
        'title': title,
        'object': product,
    }
    return render(request, 'adminapp/product_detail.html', context)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>

    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
        <script src="{% static 'js/basket_scripts.js' %}"></script>
    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="h2 text-center head">
            Админка
        </div>
    {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc_menu.html' %}
        </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
    </div>

</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="categories_list">
        <button class="new_category">
        <a href="{% url 'adminapp:category_create' %}">новая категория</a>
        </button>
		
        {% for object in object_list %}
            <div class="category_record">
                {% if not object.is_active %}
                    not_active
                {% endif %}
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                    <button>
                        <a href="{% url 'adminapp:product_list' object.pk %}">товары категории</a>
                    </button>
                    <button>
                        <a href="{% url 'adminapp:category_update' object.pk %}">редактировать</a>
                    </button>
                    <button>
                         <a href="{% url 'adminapp:category_delete' object.pk %}">удалить</a>
                    </button>
                </div>
            <div class="category_desc">
                {{ object.description|title }}
            </div>
            </div>
        {% endfor%}
    </div>
{% endblock %}

adminapp/templates/adminapp/category_create.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'adminapp:category_list' %}">
                к списку категорий
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="category_delete">
        Уверены, что хотите удалить категорию <strong>{{ object.name }}</strong>?
        <form action="{% url 'adminapp:category_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'adminapp:category_list' %}">отмена</a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ update_form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'adminapp:category_list' %}">
                к списку категорий
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="product_delete">
        Уверены, что хотите удалить продукт <strong>{{ object.name }}</strong>?
        <form action="{% url 'adminapp:product_delete' object.pk %}" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <button class="btn btn-success">
            <a href="{% url 'adminapp:product_list' object.category.pk %}">
                отмена
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="product_detail">
        <div class="product_name">
            Продукт<strong>{{ object.category.name|title }} / {{ object.name|title }}</strong> 
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href="{% url 'adminapp:product_update' object.pk %}">редактировать</a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'adminapp:product_delete' object.pk %}">удалить</a>
                </button>
            </p>
            <p>
                <button>
                    <a href="{% url 'adminapp:product_list' object.category.pk %}">назад</a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>
                {{ object.short_desc }}
            </p>
            <br>
            <br>
            <b>подробная информация</b>
            <p>
                {{ object.description }}
            </p>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_form.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form_horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить" class="btn btn-primary col-lg-12">
    </form>
    <br>
    <br>
    <button class="btn btn-warning col-lg-12">
        <a href="{% url 'adminapp:product_list' object.category.pk %}">назад</a>
    </button>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ update_form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'adminapp:product_list' category.pk %}">
                к списку продуктов
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
    <div class="product_list">
        <button class="new_product">
            <a href="{% url 'adminapp:product_create' category.pk %}">новый продукт</a>
        </button>
		
        {% for object in object_list %}
            <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                <img
                     src="{{ object.image|media_for_products }}"
                     alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href="{% url 'adminapp:product_detail' object.pk %}">подробнее</a>
                    </button>
                    <button>
                        <a href="{% url 'adminapp:product_update' object.pk %}">редактировать</a>
                    </button>
                    <button>
                        <a href="{% url 'adminapp:product_delete' object.pk %}">удалить</a>
                    </button>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                        <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|title }}
                </div>
            </div>
        {% endfor%}
    </div>
{% endblock %}

adminapp/templates/adminapp/user_form.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <form class="form_horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить" class="btn btn-primary col-lg-12">
    </form>
    <br>
    <br>
    <button class="btn btn-warning col-lg-12">
        <a href="{% url 'adminapp:user_list' %}">назад</a>
    </button>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}


{% block content %}
    <div class="users_list">
        <button class="new_user">
            <a href="{% url 'adminapp:user_create' %}">новый пользователь</a>
        </button>
        {% for object in object_list %}
            <div
                class="user_record {% if not object.is_active %}not_active{% endif %}">
                <img
                     src="{{ object.avatar|media_for_users }}"
                     alt="{{ object.name }}">
                <div class="user_role">
                    {% if object.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                <button>
                    <a href="{% url 'adminapp:user_update' object.pk %}">редактировать</a>
                </button>
                <button>
                    <a href="{% url 'adminapp:user_delete' object.pk %}">
                        {% if object.is_active %}
                            удалить
                        {% else %}
                            восстановить
                        {% endif %}
                    </a>
                </button>
                </div>
                <div class="user_name">
                    <p><strong>{{ object.username }}</strong></p>
                    <p>
                        {% if object.first_name %}
                            <b>{{ object.first_name|title }}</b>
                                {% if object.last_name %}
                                    <p>{{ object.last_name|title }}</p>
                    {% endif %}
                    {% endif %}
                </div>
                <div class="user_age">
                    age:<br>
                    {{ object.age }} лет
                </div>
                <div class="user_email">
                    email:<br>
                    {{ object.email }}
                </div>
                <div class="user_last_login">
                    logged:<br>
                    {{ object.last_login }}
                </div>
            </div>
        {% endfor%}
  </div>
{% endblock %}